### PR TITLE
Goodix fingerprint fix

### PR DESCRIPTION
**Pull request by rupansh**
fix by: p8tgames <p8tgames@users.noreply.github.com>
Co-authored-by: kalildev <kalildev@users.noreply.github.com>
Signed-off-by: rupansh <rupanshsekar@hotmail.com>

### CODE REVIEW

**Comment by erfanoabdi** [comment]
https://github.com/erfanoabdi/P_semiGSI/commit/5ba39272b4e5d93fb4b157fd534d938385aa6772

**Comment by arizaini** [comment]
why not make this commit 5ba39272b4e5d93fb4b157fd534d938385aa6772 universal to all device not just op5 family?

**Comment by erfanoabdi** [comment]
Do you know any other device with fingerprint.goodix.so?

**Comment by arizaini** [comment]
for example my device is goodix fingerprint

marlin:/ $ ls /vendor/lib/hw/fingerprint*
/vendor/lib/hw/fingerprint.default.so

marlin:/ $ ls /vendor/lib64/hw/fingerprint*
/vendor/lib64/hw/fingerprint.default.so
/vendor/lib64/hw/fingerprint.goodix.so

the other board has fpc1020 and my board goodix, ahh that marlin is from your project sGSI my original device code is "land" Redmi 3S/3X

**Pull request closed without merging**
