### PR TITLE
added lib file

### PR DESCRIPTION
**Pull request by kelvinvirani**
this lib not appears in various xiaomi device
checked on mido

### CODE REVIEW

**Comment by erfanoabdi** [comment]
there's no display config lib in /lib64 ?

**Comment by asimnisar39** [comment]
Dp4 and 5 
Front camera does not open in any app except google duo in redmi 4x gcam also not available
Any solution
In dp3 front camera work with open camera

**Comment by kelvinvirani** [comment]
@erfanoabdi there is no display congfig in lib still facing in dp5
Tested on mido

**Comment by kelvinvirani** [comment]
@asimnisar39 what error did u get try changing libs to vendor as posted on xda post???

**Comment by erfanoabdi** [comment]
Kk I'll merge it then

**Comment by asimnisar39** [comment]
'Can't open camera. Restart your device.
I restart but the problem does not solve
I tried method on xda mentioned

**Pull request closed without merging**
